export TAP_POSTGRES_HOST="localhost"
export TAP_POSTGRES_PORT="5432"
export TAP_POSTGRES_USER="northwind_user"
export TAP_POSTGRES_DATABASE="northwind"
export TAP_POSTGRES_PASSWORD="thewindisblowing"

export TARGET_POSTGRES_HOST="localhost"
export TARGET_POSTGRES_PORT="5433"
export TARGET_POSTGRES_USER="warehouse_user"
export TARGET_POSTGRES_DATABASE="warehouse"
export TARGET_POSTGRES_PASSWORD="thewindisblowing"